# Generated by Django 4.2.28 on 2026-02-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('electronics', 'Electronics'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
